"""add active col

Revision ID: 00f2bf1e37fb
Revises: f18805b2bd80
Create Date: 2025-06-03 11:04:03.704399

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "00f2bf1e37fb"
down_revision: Union[str, None] = "f18805b2bd80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auto_parts", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.alter_column(
        "auto_parts",
        "code",
        existing_type=mysql.TEXT(),
        type_=sa.String(length=128),
        nullable=False,
    )
    op.alter_column(
        "auto_parts",
        "article",
        existing_type=mysql.TEXT(),
        type_=sa.String(length=128),
        nullable=False,
    )
    op.alter_column(
        "auto_parts",
        "category",
        existing_type=mysql.TEXT(),
        type_=sa.String(length=128),
        nullable=False,
    )
    op.alter_column(
        "auto_parts",
        "subcategory",
        existing_type=mysql.TEXT(),
        type_=sa.String(length=128),
        nullable=False,
    )
    op.alter_column(
        "auto_parts",
        "product_name",
        existing_type=mysql.TEXT(),
        type_=sa.String(length=256),
        nullable=False,
    )
    op.alter_column(
        "auto_parts",
        "count",
        existing_type=mysql.BIGINT(display_width=20),
        type_=sa.Integer(),
        nullable=False,
    )
    op.alter_column(
        "auto_parts",
        "type_quantity",
        existing_type=mysql.TEXT(),
        type_=sa.String(length=64),
        nullable=False,
    )
    op.alter_column(
        "auto_parts",
        "price",
        existing_type=mysql.DOUBLE(asdecimal=True),
        type_=sa.Float(),
        nullable=False,
    )
    op.alter_column(
        "auto_parts",
        "id",
        existing_type=mysql.BIGINT(display_width=20),
        type_=sa.Integer(),
        nullable=False,
        autoincrement=True,
    )
    op.create_unique_constraint(
        "article_unique_constraint",
        "auto_parts",
        ["article", "category", "subcategory"],
    )
    op.create_unique_constraint(
        op.f("uq_auto_parts_article"), "auto_parts", ["article"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_auto_parts_article"), "auto_parts", type_="unique")
    op.drop_constraint("article_unique_constraint", "auto_parts", type_="unique")
    op.alter_column(
        "auto_parts",
        "id",
        existing_type=sa.Integer(),
        type_=mysql.BIGINT(display_width=20),
        nullable=True,
        autoincrement=True,
    )
    op.alter_column(
        "auto_parts",
        "price",
        existing_type=sa.Float(),
        type_=mysql.DOUBLE(asdecimal=True),
        nullable=True,
    )
    op.alter_column(
        "auto_parts",
        "type_quantity",
        existing_type=sa.String(length=64),
        type_=mysql.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "auto_parts",
        "count",
        existing_type=sa.Integer(),
        type_=mysql.BIGINT(display_width=20),
        nullable=True,
    )
    op.alter_column(
        "auto_parts",
        "product_name",
        existing_type=sa.String(length=256),
        type_=mysql.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "auto_parts",
        "subcategory",
        existing_type=sa.String(length=128),
        type_=mysql.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "auto_parts",
        "category",
        existing_type=sa.String(length=128),
        type_=mysql.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "auto_parts",
        "article",
        existing_type=sa.String(length=128),
        type_=mysql.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "auto_parts",
        "code",
        existing_type=sa.String(length=128),
        type_=mysql.TEXT(),
        nullable=True,
    )
    op.drop_column("auto_parts", "is_active")
    # ### end Alembic commands ###
